services:
    app:
        build: .
        container_name: laravel-app
        ports:
            - "${APP_PORT}:8000"
        volumes:
            - .:/var/www
        env_file:
            - .env
        depends_on:
            - mysql

    mysql:
        image: mysql:8.0
        container_name: laravel_mysql
        env_file:
            - .env
        environment:
            - MYSQL_ALLOW_EMPTY_PASSWORD=1
        ports:
            - "${DB_PORT}:3306"

    phpmyadmin:
        image: phpmyadmin:latest
        container_name: laravel-phpmyadmin
        env_file:
          - .env
        environment:
            - PMA_HOST=laravel_mysql
            - PMA_PORT="${DB_PORT}"
            - PMA_USER=root
            - PMA_PASSWORD=
            - UPLOAD_LIMIT=128M
        ports:
            - "8080:80"
        depends_on:
            - mysql
